### ISSUE TITLE
[Sugestion] Coast Landing button

### ISSUE THREAD

**Issue by pedroivorbgrodrigues** [Dimencia/DU-Orbital-Hud#103]
I like the coast landing feature but dont know to active it instead of breaking landing, when super heavy coast landing does the trick. Can you add a button for that too? Thank you so much for all your work.

**Comment by Dimencia** [comment]
Coast landing should automatically activate if your brakes aren't strong enough to do a regular brake-landing - in most cases it activates too often right now

**Comment by pedroivorbgrodrigues** [comment]
Thank you for your great work.
