### ISSUE TITLE
Pitch of 10deg to keep level flight

### ISSUE THREAD

**Issue by GadgetInfinite** [Dimencia/DU-Orbital-Hud#104]
Have to maintain a pitch of 10deg in order to maintain level flight, only started 20/101/2020, am looking into previous releases to see what fix started this issue

**Comment by sirbum69** [comment]
I was just going to post about this. for the last two releases i have had to keep mine at about 5-7 degrees pitch to maintain level flight. this is when flying manually with hud. but if i engage alt hold ( alt-6 ) then it pitches the nose down to 0 and stays at that height. not sure what is happening. but manual and alt hold should have to hold the same degree of pitch for level flight

**Comment by Dimencia** [comment]
Manual and alt hold may hold at different pitches, alt hold uses cruise mode, which uses all available resources (wings, vertical thrusters, brakes, regular engines) to go at the designated speed in the designated direction, so may be giving inputs that you don't see

Still seems weird though.  Still checking it out.

**Comment by ownynotavailable** [comment]
you have to align a gyro with your wings for correct alt. had the same problem

**Comment by GadgetInfinite** [comment]
What do you mean align to your wings?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Archaegeo** [comment]
If you put a gyro on your ship, you can put them on in different alignments, this fools your ship into thinking your level attitude (pitch 0 roll 0 yaw 0) is based off the gyro rather than the core if you activate the gyro (alt-9 in our hud, or manually)
