### ISSUE TITLE
[Issue] Landing Gear being activated late or wrongly

### ISSUE THREAD

**Issue by DorianTheGrey** [Dimencia/DU-Orbital-Hud#110]
Love everything about your script, only the landing gear is kind of wonky. On my L core ships the landing gear is simply being activated too late, so its still being activated when the ship hits the ground, resulting in ugly glitching at the end when the ship is being lifted slightly back to be overground after landing. Also, on AGG powered ships the landing gear seems to get confused sometimes (activating the landing gear in midair, and then pulling it in when actually landing on ground).

Is it possible to have an boolean variable to exclude landing gear management by the script? I'd rather activate and deactivate the landing gear myself.

**Comment by Archaegeo** [comment]
Please test with 4.70.  If it still occurs, provide an exact example of what you were doing and what happened.

**Comment by DorianTheGrey** [comment]
Yes, it still happens with 4.7 too.

A video says/shows more than a thousand words: [https://youtu.be/yTpTVMS1Y4s](url)

**Comment by Archaegeo** [comment]
Grab Beta 4.72 or wait for it to be pushed most likely tomorrow.  Landing Gear is fixed now and should be working well.  Landing gear is activated when you hit G to brake land ONCE you are at hover height (ground sensed).  If its not fully extending before you hit ground, thats based on your hover change rate and mass of ship and time of animation, not a lot we can do about that.

You could hit ALT-SPACEBAR as it begins its drop to hover height 0.0 and that will change hover height up till you know landing gear is fully extended and then drop rest of way.  

Ill try to schedule some additional testing to see if it would be feasible for those with landing gear to not begin the final lowering till its fully extended, but im not sure if it reports extended when you tell it to extend, or when the animation is complete, will test.

**Comment by Archaegeo** [comment]
Reopened because I just read something that made me think.  I think we have to set the hover height 0 based on landing gear, because different size landing gear holds you up different heights.

**Comment by Archaegeo** [comment]
Fixed in upcoming 4.73, target ground height user variable added to account for landing gear height when flat on ground.

**Comment by DorianTheGrey** [comment]
"If its not fully extending before you hit ground, thats based on your hover change rate and mass of ship and time of animation, not a lot we can do about that." - Yes, you can do something. Just leave the landing gear alone, put your auto-landing on ALT+G instead of G and let us control our landing gears ourselves. Often I want to lower my landing gear way before I land, using the script I can't. Of course I can go into the code and fiddle around with it myself, but I'd hate to do that every new version. :)

I think having more things optional will be the deciding factor whether people stay with your script or will sooner or later switch to a fork or different solution. Like my other suggestion to make things optional (the top information bar), a bit of personal flavor or what you want to have activated or not is a key to any complex lua-solution, I think.

**Comment by Archaegeo** [comment]
Fixed in upcoming 4.73, target ground height user variable added to account for landing gear height when flat on ground.
