### ISSUE TITLE
[Suggestion] Make top information optional or move it to the shift-menu

### ISSUE THREAD

**Issue by DorianTheGrey** [Dimencia/DU-Orbital-Hud#111]
Request to have a boolean variable to remove all the top display of the hud (maybe except mass), as I find myself not needing the information 99% of the times. I think you already did a wonderful job in reducing the HUDs visual footprint and I am sure you will have more ideas, but I'd either put some of the information into the shift-menu or enable toggling through a variable or button. What do you think?

**Comment by Dimencia** [comment]
Personally I'd rather increase the size of them - they're just too small to read at a glance, and need some contrast in them.  I feel that the size of that bar is so very small already that it wouldn't help to remove it

**Comment by DorianTheGrey** [comment]
Well, I think removing information you don't need or want is not only a compute time saver, but is also less distracting overall. Plus the "thrust needed" information is simply not useful at all as it does not help you to determine whether you can make it to space if you are sitting on the ground.

**Comment by Archaegeo** [comment]
Required thrust updates as gravity updates.  Ill consider a toggle to not draw it for those that dont want it, but not piecemeal, we have too many toggles as is (would have to be a single toggle with "codes" TMSAD or something, too complex for the value added.
(we are trying to limit code as we have limited space)
