### ISSUE TITLE
[request/fix] fuel tank optimization support

### ISSUE THREAD

**Issue by Snirp88** [Dimencia/DU-Orbital-Hud#116]
after digging through your code, it looks like the exported vars you have for tankoptimization are actually for fuel-tank handling (+20% tank capacity) but your tanks are placed down with any skills in optimization (-5% mass of fuel per lvl) the fuel percentage is calculated incorrectly. I was going to just solve for what number i'd put in your "atmo/spacefueloptimization" variable, but it looks like it will be negative and you have a > 0 check in the code.

**Comment by Snirp88** [comment]
![fuel optimization](https://user-images.githubusercontent.com/72705910/96937321-1a564780-1485-11eb-8a07-5e1247f722c6.PNG)

**Comment by Archaegeo** [comment]
Changed in 4.70
