### ISSUE TITLE
Altitude doesn't go negative

### ISSUE THREAD

**Issue by coldcycle** [Dimencia/DU-Orbital-Hud#118]
The altitude in the current hud doesn't account for negative altitude which is common underwater and on moons like Madis moon 2.
![dualuniverse_2020-10-23t15h54m04s](https://user-images.githubusercontent.com/11376103/97019542-57374280-1548-11eb-9c0d-b29b5374d969.png)

**Comment by Archaegeo** [comment]
In 4.73 the altitude will turn red if < 0m and count up as you go lower.  Note that this does not affect landing or altitude hold right now, the hovers/vBoosters still see surface of water as ground.
