### ISSUE TITLE
Request: Atmospheric altitude hold when disengaged should not set throttle to zero

### ISSUE THREAD

**Issue by JohnFHoover** [Dimencia/DU-Orbital-Hud#119]
When using altitude hold for atmospheric travel, when engaged, the cruise throttle keeping is engaged. No issues here, works as expected. 
When disengaging altitude hold, cruise is turned off and the throttle is set to zero. 
This might not be an issue for a light ship at 3000 meters, but a heavy ship at 1000 meters that just had it's engines shut off may be in for a bit more of a landing than expected.

Request: Is it possible when the altitude hold is disengaged to have the throttle set to the current position. Example, if altitude hold / cruise has throttle at 70% place throttle at 70% when altitude hold is disengaged.

**Comment by Dimencia** [comment]
I was worried about just this problem and we didn't disable cruise for a v long time because of it.  But no, we can't really calculate how much throttle% it needs to be at a certain speed, that I know of.  The best we could do would be to set some arbitrary value, like 50%, 75% or 100% thrust when it ends.  I think 50% sounds reasonable and it's enough to not kill you on warmups

**Comment by JohnFHoover** [comment]
I think that sounds reasonable, at least for testing.
But I now wonder if the disabling of cruise and then setting to 50% wouldn't still cause the engines to shutdown and then restart.
I would be interested to know if the above is the case, but I don't think it should take precedence over any real corrections or features. 

Thanks

**Comment by Archaegeo** [comment]
We have talked about this and right now cruise control is not turned off when you disengage atmo hold, it maintains current cruise setting. (tested and verified).

When you manually turn off cruise control with alt-R, vanilla DU controls sets throttle to 0.  We could possibly override this (we cant catch the alt-R, but we can monitor every tick to see if mode changed) and if mode changes, set throttle to 1% or something, but what if someone was landing using cruise control (i do, controlled 10km/hr movement to position) and hit alt-R and suddenly was under throttle.  Going to say no on this one for now but we may revisit it if there is a good method to implement.

Ill leave open for a day or two for response.

**Comment by Archaegeo** [comment]
Going to close this now.  If you come up with a good way to do this that doesnt cause crashes we can look into it
