### ISSUE TITLE
[Feature Request] Vector to Waypoint

### ISSUE THREAD

**Issue by lysol321** [Dimencia/DU-Orbital-Hud#12]
For the ultimately lazy.  Lines up on a waypoint entered manually via a variable or ingame.  Set vector to get you within an arbitrary distance for piloting in atmosphere.

**Comment by Dimencia** [comment]
Funny enough, sixtysixone, who has an autopilot that can do this in atmo, recently got in touch with me.  No promises but we'll see how that goes.
So basically, it's planned ;)

**Comment by MJLaukala** [comment]
This would be really good for space waypoints as well. My main base is a space station. Leaving it to go places is wonderful with the auto pilot. Returning; not so much.

**Comment by Dimencia** [comment]
I'm still working on this lol.  I have auto landing and auto takeoff, but, the landing doesn't really land at a predefined location, and that's pretty tough.

Space waypoints are also to-do and yeah I'll probably get them going at about the same time.  Hopefully this week

**Comment by lysol321** [comment]
All in good time brother.

**Comment by Badley187** [comment]
maybe it can work in atmo with altitude hold? then fly to the waypoint on this altitude?
btw realy good work here 👍

**Comment by Archaegeo** [comment]
Added in 4.5 just pushed.  For now it is in atmo only
