### ISSUE TITLE
Character 

### ISSUE THREAD

**Issue by ghost1257** [Dimencia/DU-Orbital-Hud#121]
When I am linked to a container hub and I get out of the seat. My character gets really buggy and my container hub reconnects and disconnects every 10 secs and then my ship starts to bug out and elements start to disappear and reappear. I dont know if this is on the lua side or the games side but to correct the situation all I have to do is relog.

**Comment by Archaegeo** [comment]
Its a DU issue that happens at high speed lately.  We all hate it, elements vanishing
