### ISSUE TITLE
Fuel tank optimization not applying correctly

### ISSUE THREAD

**Issue by Snirp88** [Dimencia/DU-Orbital-Hud#127]
seems the % of fuel of unslotted tanks goes the wrong way when fueltankoptimization is set.
Also there wouldn't be need for atmo, space, and rocket tank optimization as they are all under the same skill.

**Comment by Archaegeo** [comment]
Fuel Tank Optimization skill removed from the hud as it has no effect given how we calculate values now. Thanks for the feedback though.
