### ISSUE TITLE
Lua traceback while flying

### ISSUE THREAD

**Issue by justinbarrick** [Dimencia/DU-Orbital-Hud#129]
I got this Lua traceback in my console while flying. I was using atmospheric autopilot and it was about to initiate landing. I'm unsure if it had any negative effects, I de-activated and then re-activated my controller immediately just to be safe.

![image](https://user-images.githubusercontent.com/29671524/97409747-20f11e80-18cc-11eb-88c1-e60589344b5d.png)

**Comment by Archaegeo** [comment]
Unable to tell what the faulty function was, but thanks for the report
