### ISSUE TITLE
Auto Door / Ramp not working

### ISSUE THREAD

**Issue by neocrypter** [Dimencia/DU-Orbital-Hud#13]
I have not been able to get this feature to work, I have tried both linked to the seat and un-linked I have also had a couple people ask me about this feature in my DM's and video comments with the same issue

**Comment by paulheu** [comment]
this works as advertised, link door and/or forcefield to the control seat and rename the relevant slot to "door" and "forcefield"

**Comment by Dimencia** [comment]
Thx paul, hadn't had a chance to try it myself.  I really should get a door...

Will add that to the readme.  Closing
