### ISSUE TITLE
[Suggestion] Settings saving/loading simpler

### ISSUE THREAD

**Issue by pedroivorbgrodrigues** [Dimencia/DU-Orbital-Hud#138]
The current way that the variables are saved on the databank but not updated on the lua parameters window after load, does not seem intuitive. I find hard to keep looking at the lua chat to see the variables Im using, and it also drops the fps so I have to stop to do so. 

I find that the earliest of the implementations was clearer. The databank was the main source of truth, and the alt + 7 could wipe. Autosave on enter/leave seats is something to make the implementation easier and avoid confusion. Eveytime  you want to see what is actually being use the edit parameter window would be up to date. After script update, the autoconfigure would try to load from databank and set that on the chair so its loaded properly and the flow stays valid.

It's just one guy oppinion but I really enjoyed the old way, was not quite what I described above but was easier to understand.

**Comment by Archaegeo** [comment]
We cannot change what is shown in Edit Lua Parameters.  We can only read them or not depending on useTheseSettings button

**Comment by pedroivorbgrodrigues** [comment]
That makes sense, thank you for the info!
