### ISSUE TITLE
Altitude Hold Button

### ISSUE THREAD

**Issue by THBTX** [Dimencia/DU-Orbital-Hud#14]
Would be awesome to be able to set an altitude, or AGL and with a button, have the ship maintain that FL.

**Comment by itom-simon** [comment]
+1 - This would be a very useful feature for Atmo control.

**Comment by bizzy401** [comment]
Agreed

**Comment by itom-simon** [comment]
@dev team - thanks for the rapid turnaround on alt hold :) will test it asap

**Comment by Archaegeo** [comment]
Complete, works well, cant preset save for takeoff, but can hold any alt you are at and then adjust.
