### ISSUE TITLE
[Feature Request] Manually rename saved positions

### ISSUE THREAD

**Issue by SirProdigle** [Dimencia/DU-Orbital-Hud#141]
Would be a great help to be able to rename saved positions, either via a button such as "rename current position" on the shift menu, or even through out-of-game files, genuinely anything would be useful.

As an aside, converting bookmarks or destinations to saved positions would also be of great help. Currently the system of needing to be somewhere to save it as a destination is quite limiting

**Comment by Archaegeo** [comment]
You can update saved position now.  Select it and then choose Update when
at the new location.

The only way to get in custom names is to use an atmo radar connected to
the seat.  Then the name will use the closest atmo contact, which can be a
surfboard you spawn and rename.
