### ISSUE TITLE
[Bug] Pressing G while close to the ground always assumes landed

### ISSUE THREAD

**Issue by SirProdigle** [Dimencia/DU-Orbital-Hud#142]
Pressing G while flying low assumes a grounded position, ideally if thrusters are active or the brakes are not enabled, then G in any situation should disable the both and initiate landing. 

A problem scenario would be flying close to a platform at a low speed to land and pressing G, even if thrusters were at 20% all that would happen is the gear coming out, with breaks off and thruster speed the ship would still crash.

Solution: If brakes are turned off or thrusters are enabled in any capacity then the G key should break, 0% thruster, and initiate landing

**Comment by Archaegeo** [comment]
Fixed in 4.811.  If you are within hover distance brakes will apply as well as extending gear..  I did not 0 thruster as you some might want to push against brakes.
