### ISSUE TITLE
Lag issue

### ISSUE THREAD

**Issue by mchloupek** [Dimencia/DU-Orbital-Hud#144]
Occasionally when you jump into hovercraft equipped with the script, you experience serious lags. This happens once in 10 or 20 attempts.  My experience is from the ground on several planets. This can be solved by leaving the hovercraft and jumping in again or of course by restarting the game. While using hovercraft with game default script I have never experienced this issue nor with another script, I've tested for several days.

**Comment by Archaegeo** [comment]
This happens not due to hovercraft, but with any hud that draws on the monitor.  It happens when you hit Tab and click on a non-clickable area.  You can fix it with alt-3 till you can safely land and resit.
