### ISSUE TITLE
Resolution positioning problem

### ISSUE THREAD

**Issue by Lokiet** [Dimencia/DU-Orbital-Hud#170]
I updated the program, changed the resolution, but found that the information bar and the notice text are pushed to the right side of the screen. I fitured out how to center the altimiter, thruttle and fuel, but cannot seem to move the top most information screen and the notice screen (the invisible screen which tells me things like breaking, landing, and gear extended and hover height). Which setting am I missing for these windows?

![image](https://user-images.githubusercontent.com/74410179/100231867-96fd9b00-2ef5-11eb-81e4-a18ccf0a131e.png)

**Comment by avalon666** [comment]
I had the same problem. Once reloading the script into the chair fixed the bug. Setting default resolution. Monitor 1680x1050

**Comment by minimeijertje** [comment]
![image](https://user-images.githubusercontent.com/5476469/101407297-f5a21c00-38da-11eb-9006-24c52918a1c4.png)
I think i have the same issue.. reloading the script did not fix it:(

**Comment by h-zone** [comment]
im add some suggestions
https://github.com/Dimencia/DU-Orbital-Hud/issues/194

**Comment by Archaegeo** [comment]
Fixed in 4.910, should work for most if not all resolutions now.
