### ISSUE TITLE
Uncontrollable Altitude Adjustments

### ISSUE THREAD

**Issue by konvic21** [Dimencia/DU-Orbital-Hud#176]
Whenever I have to control the altitude for any feature of the HUD with the ascend/descend shortcuts, be it AGG, autopilot or hold altitude, the adjustments start to speed up to inhuman speeds after a few adjustments. I am unable to adjust the target altitude correctly if I try to adjust it a few times in one seating.

It would start to change faster and faster(to multiple SU per change). I would have to get out and back into the seat to reset the speed at which the altitude changes.

I have not seen this reported previously, I do not know if it is just me and I am doing something wrong. Please help.

**Comment by Archaegeo** [comment]
Altitude adjustments (alt-c and alt-spacebar) should be done in spurts.  It speeds up the longer you hold it on purpose.  It should reset its speed change when you release it for a moment.

**Comment by konvic21** [comment]
Thanks, I guess it's an issue on my end then as it does not reset no matter
how long I release it so long as I am in the seat.
