### ISSUE TITLE
Cruise Control in space

### ISSUE THREAD

**Issue by bizzy401** [Dimencia/DU-Orbital-Hud#178]
Whenever cruise control engages when the space engines are working it feathers the brakes at 50 kph. I enter Sanc at 1800kph at 18000m up and it auto does this, making glide reentry useless. Maybe I am doing something wrong?

**Comment by spommerening** [comment]
Same here. What I do is dipping the nose down to 30-40 degrees in order to increase speed both forward and downward. 
But I totally agree, I don't think this is working as intended - or we are doing something wrong ;-)

**Comment by Archaegeo** [comment]
This is a ship by ship issue.  For large or unique ships the HUD glide re-entry can be pesky, this is a DU (not HUD) issue.

Cruise control as done by DU is wonky in that it seems to want to maintain the max vector you are going at the target speed you are set.  So if you find yourself into a more falling than forward vector, its going to try to maintain you at your preset speed by blasting engines full and while braking full.

The best way to do a glide re-entry is to align prograde first while < 20000m and preferrably < 3000km/hr.  Then do the glide re-entry button.
