### ISSUE TITLE
Vertical speed

### ISSUE THREAD

**Issue by Ruderali** [Dimencia/DU-Orbital-Hud#18]
New to LUA and DU, mainly work in Python, C# or Java. Has someone written a vertical speed indicator? I want to build an auto orbit and I want someone smarter than I to make an auto lander. But vertical speed will be needed. What would I need to call to get something like this to work.

`
alt = getAltitude() 
sleep(1)
newAlt = getAltitude()
verticalSpeed = newAlt - alt  
`
Ideally drop sleep() to 0.01 or something and multiply verticalSpeed to compensate but I'm not sure how laggy it would be. Then it would just be a matter of basically locking the pitch to +8 degrees, keeping the speed below 1000 while in atmo. Then burning prograde until Ap is at the desired altitude and waiting for Ap to circularize. Although a better implementation could be to just burn prograde until Ap is well above desired alt and then burn anti-normal until circularized to save some time at the expense of fuel. OFC a really basic implementation but it should work for most usecases until someone comes up with something that takes the individual ship's lift and TWR into account.

**Comment by paulheu** [comment]
This should really go into the #lua-scripting channel on the DUscord https://discord.gg/dualuniverse

**Comment by cola98765** [comment]
```
local Vx = core.getWorldVertical()[1]*core.getWorldVelocity()[1]
local Vy = core.getWorldVertical()[2]*core.getWorldVelocity()[2]
local Vz = core.getWorldVertical()[3]*core.getWorldVelocity()[3]
local V = (Vx+Vy+Vz)*-1
```
V is your vertical speed... It's not the best code, but it works.

**Comment by Dimencia** [comment]
Closing, I barely have time to keep up with the bugs, sorry can't really help with stuff like that.  Post in the lua channel in the DU discord and, I'll probably be there. lol
