### ISSUE TITLE
Keyboard Controls Still Involve Mouse

### ISSUE THREAD

**Issue by Trotsky21** [Dimencia/DU-Orbital-Hud#180]
This may be WAD.

Of the three control options, one is shown as "Keyboard", while the other two involve the mouse to some extent. However, when using the "Keyboard" option, the mouse still has flight control - that is, when I move the mouse it is exercising some control over the craft. 

Control schemes should either be changed or re-labeled to reflect what actually happens. Personally, would prefer a control scheme that doesn't involve the mouse (except the wheel for throttle).

**Comment by Archaegeo** [comment]
You set the seats control scheme to keyboard, then you set the HUD to keyboard, mouse, or virtual joystick.

This mirrors vanilla to a great extent save where things are changed for enhanced flight control.
