### ISSUE TITLE
4.850 update

### ISSUE THREAD

**Issue by ghost1257** [Dimencia/DU-Orbital-Hud#186]
Hi, I downloaded the latest update for the AutoPilot and there is no Autopilot it looks like the normal flight API. I love your Lua Program but it is broken right now. just thought I would let you know. PS. I didnt download the wrong one which i mean the one without Autopilot.

**Comment by FarmerJack** [comment]
Same. Older versions (4.811) still partially work but 4.850 does not seem to load at all after following updated instructions

**Comment by ghost1257** [comment]
aim at your chair do cTrl + L then just hit apply and should be fine this
is the fix for it. I went to discord for help.

**Comment by wristy1627** [comment]
question how do we use rocket engines to lift a ship up as org has a ship too heavy for normal lift

**Comment by ghost1257** [comment]
you want to put the ship in cruise control and set the speed and press b
also i have never messed with rockets
