### ISSUE TITLE
Wide screen support, grid overlay suggestion

### ISSUE THREAD

**Issue by h-zone** [Dimencia/DU-Orbital-Hud#194]
hey!

i have a wide screen (3440x1440), and too many options need to scale and calculate to place script widgets to the hud.
can You adopt the script to work not from 1920x1080 pixels but from viewHeight/viewWidth units?

and/or suggest a grid with cross points with the pixels positions as turnable overlay.

in example squares from a center with side of 640px...

**Comment by Archaegeo** [comment]
New resolution support in 4.910 (pushed now)  Let me know if still issues.
