### ISSUE TITLE
Framerate drop dramastically

### ISSUE THREAD

**Issue by 4lador** [Dimencia/DU-Orbital-Hud#2]
When using the script, the framerate drops dramastically and the game become really slow, when I change lua configuration to default it's ok.

(nice job with this script btw)

**Comment by Dimencia** [comment]
Ty, and sorry to hear about that.  There is a current bug (as far as I can tell) that if you have a radar, lua HUDs tend to cause significant framerate drops.  I'm ... still working on getting a radar so I can investigate, and hopefully make a replacement for the radar widget that doesn't cause problems.
Also it seems that if you press tab and click anywhere that's not a button, whether using a custom HUD or not, the game lags aggressively until you exit/re-enter the cockpit - just want to confirm that's not what you did?

**Comment by busbyra** [comment]
I tested this out without a radar and noticed the framerate drop. Seems to be tied to tickrate.  I'll play with it more later.

**Comment by Dimencia** [comment]
What are your PC specs?  I wouldn't expect them to really matter considering it's just LUA but... it's... doing a lot of math.  But my processor is kind of ass and it does okay for me (GPU is good tho).  
You can try bringing down the tickrate in unit.start (at the end), but less than 30fps starts to look even worse than before, and you might encounter more inaccuracy with the autopilot

**Comment by rosudrag** [comment]
I'm experiecing severe fps drop after couple flights during same game session. By flights I mean going A->B exiting seat and going next location. Restarting game seems to reset it.

**Comment by LiPeK** [comment]
I also noticed frame rate drops, especially when I'm in orbit. Maybe its related to Orbit Map window in upper left corner that shows up.

**Comment by Archaegeo** [comment]
We have found that FPS tanking occurs with any HUD when you click on other
screens in DU, ive had it happen with achievements.

**Comment by busbyra** [comment]
CPU 3700X
GPU 5700XT
RAM: 32Gig at 14-14-16

Set the timer refresh rate to .5 seconds and watch the world look weird.

Tabbing in and out of the game also speeds up the process of killing the fps with this on.

I ran your setup on someone else's ship for about 20 minutes before noticing the FPS beginning to drop.  I don't think it's your code that is the issue specifically.

**Comment by red15** [comment]
This is related afaik to the GC that the lua is doing. Overwriting the html content leaves the old html content to be picked up with the GC and that can cause problems after a while.

**Comment by njmill** [comment]
@Dimencia If you still need some radars to test with, I can give you some.  
For the framerate issues, the current popular workaround is to put the HUD on a programming board, and activate it after you mount the command chair.

**Comment by Dimencia** [comment]
Framerate issues have been (mostly) resolved by removing all transparency and general optimization.  Please reopen a ticket if it continues to give you trouble
