### ISSUE TITLE
How do I get rid of the rocket booster code?

### ISSUE THREAD

**Issue by captkellix** [Dimencia/DU-Orbital-Hud#20]
I tried to remove the rocket booster code but seem to have missed a step somewhere. What all needs to be changed to get rid of that portion of the LUA?

**Comment by Archaegeo** [comment]
Change `        actionStart:
            args: [booster]
            lua: |
                --Nav:toggleBoosters()
                -- Dodgin's Don't Die Rocket Govenor - Cruise Control Edition
                isboosting = not isboosting
                if(isboosting) then unit.setEngineThrust('rocket_engine',1)
                else unit.setEngineThrust('rocket_engine',0)
                end
`  to `actionStart:
            args: [booster]
            lua: Nav:toggleBoosters()`
also get rid of `                isBoosting = false -- Dodgin's Don't Die Rocket Govenor - Cruise Control Edition` and `                -- Rockets
                Nav:setBoosterCommand('rocket_engine')
                -- Dodgin's Don't Die Rocket Govenor - Cruise Control Edition
                speed = vec3(core.getVelocity()):len() 
                cc_speed = Nav.axisCommandManager:getTargetSpeed(axisCommandId.longitudinal)                
                if(speed * 3.6 > cc_speed) then 
                    unit.setEngineThrust('rocket_engine',0)                
                else if(isboosting) then 
                    unit.setEngineThrust('rocket_engine',1) end                
                end
`
