### ISSUE TITLE
No database found although available

### ISSUE THREAD

**Issue by avalon666** [Dimencia/DU-Orbital-Hud#204]
With the version 4.900 I had so understood that one must dismantle the seat and the database and set again. After I did that and loaded the new version of the script it says that there is no database although it is there and linked to the chair. This problem also exists when I create a new construct with a new seat and a new database. 
Only loading the script in version 4.858 solves the problem and it finds the database. After that I can also use version 4.900 or 4.901.

**Comment by avalon666** [comment]
Just noticed that with the version also no longer saves navigation points, delete or update.

**Comment by Archaegeo** [comment]
Just tested, working fine for me, closing this, please use the discord if still experiencing issues.
