### ISSUE TITLE
standard "angle_between" works wrong

### ISSUE THREAD

**Issue by SvarogZ** [Dimencia/DU-Orbital-Hud#217]
There is no clamp in the standard function. It should be replaced.
```
-- instead of standard function
function angle_between(vector1,vector2)
	return math.acos(utils.clamp(vector1:dot(vector2) / (vector1:len() * vector2:len()),-1,1))
end
```

**Comment by Archaegeo** [comment]
If it is truly wrong, recommend letting NQ know since it is in vec3.lua a default DU file.  In our code it works fine for getHeading which is the only place its used (to draw the compass up top when in world)
