### ISSUE TITLE
Mouse is way less responsive than before

### ISSUE THREAD

**Issue by TheGeek007** [Dimencia/DU-Orbital-Hud#219]
Since 4.925, the mouse control mode is less responsive. IE the mouse is moved a high amount, and the ship turns a very small amount. Adjusting the mouse sensitivity doesn't appear to help. Values from 5 to 0.005 were tried.

**Comment by TheGeek007** [comment]
Oops. Didn't read the manual. Those mouse sensitivity values are for virtual joystick.
Anyways, issue still stands. Reverted back to 4.923 and the issue seems to have gone away.

**Comment by Archaegeo** [comment]
Fixed in 4.926 (coming soon, and the problem was not in 4.924 either)  Thanks for the feedback
