### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by The1Ulost2** [Dimencia/DU-Orbital-Hud#22]
What lines do i need to disable to not have the kerbel space window? When near a planet I feel like I get a lot of lag when that thing is up could be a coincidence but honestly I don't need the window anyway.

**Comment by Archaegeo** [comment]
The lag has nothing to do with the kerbal window, tested that today with HUD off.

But to turn it off full, just comment out DisplayOrbit() in two places (but not the function definition, though you could remove that whole section too)
