### ISSUE TITLE
/addlocation seems to give me some point on Alioth no matter what coordinates I enter.

### ISSUE THREAD

**Issue by Splutty** [Dimencia/DU-Orbital-Hud#221]
See Subject. It seems to always add "Alioth" as the waypoint, no matter which coordinates I actually paste.

**Comment by Archaegeo** [comment]
If you are pasting the ::pos from clipboard, it should be working, recommend retrying.  Ill verify later

**Comment by Archaegeo** [comment]
Just flew to Sanctuary, used /addlocation Sanctuary-TCU ::pos{0,26,-41.5833,147.1777,73.3664}   and it worked perfectly.  Closing this

**Comment by Splutty** [comment]
What might be wrong instead of the location, is the "Distance" measurement. I'm on Sanc, added the position you tried, and I get this a Distance of 7.6 SU.
