### ISSUE TITLE
Auto Pilot failure.

### ISSUE THREAD

**Issue by Splutty** [Dimencia/DU-Orbital-Hud#222]
When you're autopiloting to another planet, but fail to break atmo because of weight, the autopilot will keep trying to get back into space, even when activating the autopilot to a location on the planet you couldn't leave.

**Comment by Archaegeo** [comment]
Umm, if you dont have the engines to break atmo at your angle you have to adjust either max up angle or change engines etc.  I would never leave an autopilot before its broken out of atmo, so you can always hit alt-4 again to turn it back off.   Will make sure it resets space takeoff if you choose a new autopilot.

**Comment by Splutty** [comment]
The atmo thing was just a symptom, the actual cause appears to something else.

I have one location that's just simply stuck at wanting to ascent to 100.0KM, and I can't get it to not do that, whereas other locations near that one don't exhibit that issue. The only way I'm now able to stop it from trying to climb to 100KM is to remove the location and re-add it, at which point it goes back to trying to climb to 1KM when engaging the autopilot.

It's not a space location, it's not a location that should ever want to go to space, it's 19.7KM away from where I am.

I don't know what causes it, but I'm trying to reproduce it reliably. This particular one happened when I initiated autopilot from under water.
