### ISSUE TITLE
[feature request] export parm for initial groundalt after liftoff

### ISSUE THREAD

**Issue by itom-simon** [Dimencia/DU-Orbital-Hud#23]
As I'm departing from a hangar, I need to set the initial altitude (after pressing G to launch) to a height which will fly through the door. Can you please set the initial alt as an external parm? 
Thanks

actionStart:
            args: [gear]
            lua: |
                gearExtended = not gearExtended
                if gearExtended then
                    if AltitudeHold and (vBooster or hover) then -- If they extend while holding and we can get distance, land
                        AutoLanding = true
                        gearExtended = false -- Don't actually do it
                    else
                        Nav.control.extendLandingGears()
                        Nav.axisCommandManager:setTargetGroundAltitude(0)
                    end
                else
                    Nav.control.retractLandingGears()
                    **Nav.axisCommandManager:setTargetGroundAltitude(500) -- What's max?  Req: make this a parm**
                end

**Comment by itom-simon** [comment]
... actually - hold off on this - just read about the new auto-takeoff with a preset alt - that might do what i need

**Comment by Archaegeo** [comment]
Yep, should be what you need. otherwise the settarget is limited to the range of vertical boosters
