### ISSUE TITLE
Permanent stall warning

### ISSUE THREAD

**Issue by T4R4N1S** [Dimencia/DU-Orbital-Hud#230]
Hello. Please where could be the problem with script or ship or both? When the speed during flight reaches sustentation speed then always stall warning alarm appears on screen. Even if I am flying almost 1000 km/h and climbing properly or holding altitude without any problem. thank you for any suggestion. BR. Tar.

**Comment by Dimencia** [comment]
This should be fixed on the latest Beta branch, but it needs further testing before pushing to master because the branch includes some major changes to atmo flight.  I would advise either rolling back or trying Beta (and let us know of any problems, or successes, with it)

**Comment by T4R4N1S** [comment]
Latest BETA working correctly. Good work.
