### ISSUE TITLE
 Big update = big issue

### ISSUE THREAD

**Issue by Villzzzz** [Dimencia/DU-Orbital-Hud#25]
Currently (V3.6) shortly after take off script stops working. Graphic of HUD is frozen - joystick control doesn't work

**Comment by Archaegeo** [comment]
Did you set your vehicle to Keyboard first per the readme?

**Comment by Dimencia** [comment]
If this happens again, make sure to try to get out of the seat, edit lua, and take a screenshot of any errors it might be showing (if you're not too busy crashing and burning)

**Comment by Villzzzz** [comment]
Now it is working
