### ISSUE TITLE
Losing braking metrics 

### ISSUE THREAD

**Issue by tintreach** [Dimencia/DU-Orbital-Hud#26]
I've seen this in 3.5 and 3.6
When exiting the seat while "Cruising"
On reentry to the seat and setting back up auto pilot, all braking data is lost
![Screenshot (7)](https://user-images.githubusercontent.com/26555766/94344281-25d06300-ffec-11ea-94b6-de86d6d40fef.png)

**Comment by tintreach** [comment]
W/A.....
Enable then Disable Turn and Burn
Reloads the braking data

**Comment by Dimencia** [comment]
Should be fixed as of when I went to be about 7 hours ago, was just too tired to reply.  Let us know if it persists
