### ISSUE TITLE
Option to use remote control with hud

### ISSUE THREAD

**Issue by schmas** [Dimencia/DU-Orbital-Hud#27]
Would be great to have an option to use the HUD on the hoverboard. Having the HUD and be able to control normally with keyboard, mouse. Maybe an option at the parameters to set remote control with follow (which is great by the way) or normal remote control (that freezes the player). 

What do you think?

And congratulations, fantastic stuff here.

**Comment by Archaegeo** [comment]
Why cant you do this already?

**Comment by Archaegeo** [comment]
Verified, works fine on a surfboard.
