### ISSUE TITLE
Brake landing crashes ship

### ISSUE THREAD

**Issue by smessmer** [Dimencia/DU-Orbital-Hud#274]
When trying to brake land, it descends with ~180-200 km/h, which crashes my ship. I'm running v5.450.

Things I checked:
- The ship has enough brakes. If I just press "Ctrl" in mid flight (i.e. not using the HUD brake landing capability), then it slows down to about 40-50 km/h and slowly descends.
- The CalculateBrakeLandingSpeed setting is disabled
- brakeLandingRate is set at 30, so that should limit it to 108 km/h if I did my math correctly.
- I tried enabling brake landing from very large heights. It immediately slows down to the 180-200 km/h and then stays there until it crashes into the ground.

Note that my ship has a very large amount of air brakes. Maybe the script somehow fails to activate them all?

**Comment by smessmer** [comment]
I confirmed that it's an issue with the HUD script. The same ship and same cargo when using the default autoconfigure (and just holding Ctrl for braking) can brake-land fine. But when I install the HUD script, and use the Brake lock (i.e. toggle the brake on with Ctrl), then it only sets each brake to ~1MN braking force instead of the 7MN each brake would be able to do, and the ship crashes into the ground.

**Comment by smessmer** [comment]
Update: just pressing Ctrl with the hud script now also doesn't work, seems to have been a fluke. Only the stock autoconfigure script can reliably brake land my ship

**Comment by smessmer** [comment]
Another thing I just noticed: when trying to brake land, while flying, and also while braking down to 200-300 km/h, the UI shows a "Max Brake" of around 250.000kN. but as soon as it has braked down to around 200-300kN, the "Max Brake" value drops significantly. So it seems the script is still applying the "max Brake", but my ship heavily loses "max Brake" capacity when slower? This seems super weird. Note that the Alt+3 UI shows the same decline in max brake force. I would think it a DU bug but then there's the thing that the autoconfigure script works fine...

**Comment by smessmer** [comment]
Ugh in the current attempt, the same thing happened with the autoconfigure script. Max brake dropped and I crashed. Seems it isn't an issue with the hud script after all but something in DU.

**Comment by smessmer** [comment]
Hm at least some fluctuation in "Max brake" also happens in successful landings where it is able to slow down to 100 km/h

**Comment by smessmer** [comment]
Ok I've tried a few more times and the stock autoconfigure script almost always works while the DU hud script almost always crashes the ship

**Comment by Dimencia** [comment]
Sorry for the delay, missed these issues, but it's also unfortunately not something I can help with - as far as I know, it's a DU bug for particular constructs where sometimes, their brakes just don't work anymore.  I've seen it a few times, and have confirmed on streams that it seems random and, in our testing, didn't seem related to having HUD or not - and was one specific ship having the problem, most ships never see it
You can try updated versions, or try ArchHUD, but mostly I'd recommend re-deploying the ship BP.  In particular, make sure the databank is cleared, and make sure to check the UseTheseSettings box (or even better, use the chat commands) when setting things.

It is also possible it's just some intermittent obstruction on the brakes.  Brake force in atmo should decrease as speed decreases, though, that's normal
