### ISSUE TITLE
[Feature Request] Auto Pilot Fuel Economy Mode

### ISSUE THREAD

**Issue by LumberingTroll** [Dimencia/DU-Orbital-Hud#30]
Would you be willing to add a couple of buttons to toggle a fuel economy mode to the autopilot?
Currently, the AP burns at 100% thrust until the max velocity is achieved, I usually limit mine to around 70% as it makes you fuel last much longer but takes longer. Anything above 50% has major diminishing returns for the burn to thrust ratios. 
Id appreciates a 50%, and a 75% setting. 

When I go to thades on my own I usually have 5 - 10% space fuel when I get back to sanc, but AP used all of it accelerating on the return trip to sanc, and now I have no fuel for maneuvering on reentry.

**Comment by Dimencia** [comment]
Done, latest update gives you a parameter to set this.  It also no longer locks you in, so, you can adjust it while you're flying if you want.
