### ISSUE TITLE
On-Screen Button to change Brake (Toggle/Press2Engage)

### ISSUE THREAD

**Issue by THBTX** [Dimencia/DU-Orbital-Hud#31]
Add an on-screen button to allow us to change from press to engage braking to toggle.  With on-screen indication of setting.

**Comment by Dimencia** [comment]
Done, latest update.  That brake button on the HUD was useless anyway ever since I moved the key from Ctrl to Shift

**Comment by THBTX** [comment]
Oh boy.  Sorry gang, ya'll were ahead of me!
