### ISSUE TITLE
Script error - BreakToggle nil value

### ISSUE THREAD

**Issue by Villzzzz** [Dimencia/DU-Orbital-Hud#33]
![image](https://user-images.githubusercontent.com/71701025/94361712-ba06fc80-00b6-11eb-8ae3-03499b60a193.png)

I just took V3.799 and I got  following script error

**Comment by f3rr311** [comment]
All items I have put the 3.799 on also have this issue 


![dualuniverse_2020-09-27t04h59m54s](https://user-images.githubusercontent.com/14023914/94364473-5234bf80-007e-11eb-98df-c730369b404f.png)

**Comment by itom-simon** [comment]
yes, i can confirm that 3.79 and 3.799 result in script error on activating seat - 3.5 is ok

**Comment by ottodeluxe** [comment]
Can confirm, 3.7X and 3.8 are affected

**Comment by toepick** [comment]
Same, script error and brake doesn't work at all. Using the hover seat; same with the remote control.  Started with 3.7X.

**Comment by Dimencia** [comment]
Found and resolved.  Don't ask why it only showed up for some people and not others.  No idea.
