### ISSUE TITLE
Screen orientation locked when using keyboard-only controls, when interplanetary helper is displayed

### ISSUE THREAD

**Issue by jpentland** [Dimencia/DU-Orbital-Hud#34]
Steps to reproduce:

* Run DU Orbital HUD autoconfigure script
* Edit Lua Parameters and set userControlScheme to 'Keyboard'
* Enter contol seat
* Use mouse to freely look around
* Press alt+f1 or alt+f2 to open interplanetary helper
* Mouse no longer has any effect on camera orientation, may be stuck at an awkward angle

**Comment by Dimencia** [comment]
Alt is a freelook toggle by default.  You can adjust this in the lua parameters if you prefer it to be a hold to look.  It cannot lock forward in the first third-person mode when you turn it off - press Insert a second time to get to a view that is locked forward if you need this

But, I just realized you keyboard players aren't used to freelook existing at all, and it really doesn't have to on keyboard.  Uploaded version where keyboards have freelook on at all times

**Comment by LoneBoco** [comment]
@Dimencia commit https://github.com/Dimencia/DU-Orbital-Hud/commit/45e6505bf63d04bc5ade6a2060fa6e9826fc9c9e reverted this fix.  Was that intended?

**Comment by Dimencia** [comment]
Yep, the buttonsHUD can't be shown while in freelook, so there must be a camera lock option for keyboard players.  There is a LUA parameter for FreelookToggle that you can turn off, but it still can't snap your view forward in the second View mode, so use either the first or third if this is a requirement
