### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by spainchaud** [Dimencia/DU-Orbital-Hud#35]
Version 3.81. I loaded the script onto a simple atmospheric flyer, no space elements. I got a script error and no HUD showed up. I traced the problem to lines 413 and 414 which I commented out. The script seemed to work fine after that. Here are the line I commented:

                        gearExtended = true -- Show warning message and set behavior
                        Nav.axisCommandManager:setTargetGroundAltitude(targetGroundAltitude)

I don't know what these lines do, so I don't know if I am missing some feature.

**Comment by Archaegeo** [comment]
This has been fixed as of 3.80,  please update.
