### ISSUE TITLE
[Feature Request] Toggle Vertical Boosters / Hovers

### ISSUE THREAD

**Issue by Midius** [Dimencia/DU-Orbital-Hud#37]
Hey,

First on I really love your project and I think it's coming along very nicely!

I would love to see an option where you can tell the construct to only use Vertical Boosters, when there is no atmosphere. VB are super inefficient and it's always a waste of fuel when they activate on Alioth even if the Hover engines alone would be quite enough to hold the ship up. It would be amazing if it could automatically activate the Boosters if that's not the case, but I could live without that.

The problem is, that I didn't find a convenient way to deactivate the booster engines without adding all boosters to the control unit. But with large ships having many fuel tanks and many Boosters you would run out of connections pretty fast. Maybe you have more luck with that problem.

keep up the good work!

**Comment by Dimencia** [comment]
This is actually really, really hard (I saw some people going over it in the LUA channel)

Basically, the game does its own fancy calculations for how much thrust to give your VBoosters/Hovers to put it at the height you want.  If I turn off VBoosters, that calculation becomes wrong and your ship is likely to hit the ground


But, I think there's a workaround I heard about.  I will leave this open until I can look into it further (might be a while)

**Comment by Midius** [comment]
I feared exactly that.

I don't have much time this week, maybe I get the chance to take another look at it next week. But I would be interested in that workaround if you mind sharing the info.

**Comment by Dimencia** [comment]
I'd have to dig it back up for the details, I know LloydChristmas had a conversation with someone in the lua channel about it (so maybe search for his messages but, good luck he helps everyone :P )
But basically he mentioned that the best bet is to somehow set an engine priority so that hovers are preferred and that's it.  But IDK how to do that

**Comment by Midius** [comment]
Hmm yeah that would mean ditching the automated hover routines all together and making one yourself. 
It would be possible, it's practically the same logic I used for my space elevator when I think about it.
