### ISSUE TITLE
Framerate Drops after clicking

### ISSUE THREAD

**Issue by Midius** [Dimencia/DU-Orbital-Hud#38]
I still expirience extreme Framerate drops after klicking anywhere when the HUD is active.

Everything works perfectly until I hit Tab and klick anywhere, after that it is just lagging and unplayable. Leaving and entering the Control unit solves the problem imidiatly. I can reliably reproduce this every single time.

Running Version: 3.84 (Downloaded just a few minutes ago)

**Comment by Archaegeo** [comment]
This is an issue with DU that has to be solved by NQ as far as we can tell.  We have not discovered anything related to this other than the face we print html on the screen.  We believe it would occur if we did nothing but print HELLO on the screen.  The only thing you can do at this point is exit and reenter the seat (or remote).  We know this isnt ideal, but its currently the only solution we can find.
