### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by MJLaukala** [Dimencia/DU-Orbital-Hud#39]
The ability to display the name of the tanks instead of "[type]Fuel [n]". It might be best if it were an option via params. I often use tanks for specific tasks so in my case, it's really handy to know what tanks are low. Some can be ignored if they are low, some can't. I don't have that info with the current default iteration.

**Comment by Archaegeo** [comment]
Version 3.87
- Renamed fuel tanks will display their name on the fuel status (up to 12 characters)
