### ISSUE TITLE
Downward facing engines

### ISSUE THREAD

**Issue by ghost1257** [Dimencia/DU-Orbital-Hud#41]
when going to land the downward facing engines dont shut off like the hovers is there a way to keep the downward facing engines and have them work like the hovers

**Comment by Dimencia** [comment]
As far as I can tell, there's a bug in the most recent patch of DU that makes this happen.  Also happens in space - translation thrusters never really stop firing even between planets.  Try it with default Flying Construct and you'll likely see the same behavior - I know my space engines do it whether I'm on default or not
