### ISSUE TITLE
Resolution fix

### ISSUE THREAD

**Issue by keimond** [Dimencia/DU-Orbital-Hud#42]
I'm not sure what the wording is for this.. I have one buddy who says the graphics and text are very small on his HD monitor. I have a 4K monitor and play in a 2560x1440 window.

![image](https://user-images.githubusercontent.com/1580514/94475366-31f32680-018c-11eb-9675-1bb5be900298.png)

**Comment by Archaegeo** [comment]
our hud does not work in a cockpit.

**Comment by keimond** [comment]
ah shoot I'm sorry my mistake, I'll try it on a chair and see if I get the same results.

**Comment by keimond** [comment]
yes sir that was the issue.
