### ISSUE TITLE
Rocket booster

### ISSUE THREAD

**Issue by zyfiria** [Dimencia/DU-Orbital-Hud#43]
can find the way to turn them on
the UI says press B but to no end sadly
ok i have been able to make it work but i just don't understand how i did it
would you plz explain more because my english ok but not that good sadly

**Comment by Dimencia** [comment]
The Boosters only work in Cruise Control because of Dodgin's Don't Die Rocket Booster

1. Turn on cruise control
2. Set desired speed
3. Press B for rockets to fire up to that speed
