### ISSUE TITLE
When using keyboard mode, you are unable to use the on-screen buttons.

### ISSUE THREAD

**Issue by LoneBoco** [Dimencia/DU-Orbital-Hud#44]
The shift key does not show the buttons when you set the control scheme to keyboard.  I was able to fix it by always allowing the lshift action when in Keyboard mode:
https://github.com/Dimencia/DU-Orbital-Hud/blob/4825ad1e4c93c157a19422036a48f73c419b49fa/ButtonHUD.conf#L4128-L4132
https://github.com/Dimencia/DU-Orbital-Hud/blob/4825ad1e4c93c157a19422036a48f73c419b49fa/ButtonHUD.conf#L4136-L4141

```lua
if system.isViewLocked() == 1 or userControlScheme == "Keyboard" then
    HoldingCtrl = true
    PrevViewLock = system.isViewLocked()
    system.lockView(1)
end
```
It seemed to work fine, but I haven't really tested things in-depth.

**Comment by Dimencia** [comment]
The view must be locked for the buttons to show, otherwise using the mouse cursor will make you look around everywhere and it's wonky and disorientating.  LAlt is the default view lock/unlock key

**Comment by LoneBoco** [comment]
@Dimencia The above changes I made lock your view while holding left shift, though.  I never felt like anything was off when using it.  I can free look normally but, when I hold left shift, my view snaps and locks back to the front and I can select buttons.  Letting go of left shift re-enables free look.

**Comment by Dimencia** [comment]
Enforcing view lock on Shift causes people to be unable to use Shift+Scroll to zoom in/out in third person views, so the viewlook must be toggleable on a different key to retain this option.  This is a good solution for you, but many others who use third person would be upset about being unable to zoom out, so unfortunately it's not generic enough
