### ISSUE TITLE
[Feature Request] Configurable speed increments

### ISSUE THREAD

**Issue by GeneralTragedy** [Dimencia/DU-Orbital-Hud#48]
Currently scrolling the mouse wheel increments speed by 10% per tick, and using R/T increments by 25% per tap (I believe...). Whatever the exact current values are, it would be great to have these %'s configurable in the Lua parameters.

**Comment by Archaegeo** [comment]
Done, will be in 4.06  two user variables that control the rate of change when using speedup/down.
