### ISSUE TITLE
[Feature Request] Companion Display Board Module

### ISSUE THREAD

**Issue by wescrockett** [Dimencia/DU-Orbital-Hud#54]
I would love a LUA module to display the Autopilot/Target Destination data on a Small or Medium display. This would be great for when multiple people are traveling together so the passenger can see orbital ETA, time to Brake, etc... I was looking at the code to see if I could make heads or tails of it and so far, I have been unable.

Someone on the DU Discord mentioned that one should be able to take that piece of LUA from the autopilot script and paste it to the display board... I'm not certain it's that easy though.

**Comment by Dimencia** [comment]
It kind of is.  It's kind of as simple as connecting a screen to the seat, named 'screen' in the slot, and doing screen.setHTML(content) somewhere after we updateHud()
But, something about the way we're doing it on the HUD makes it look horrible on a screen, low res and just not good.  So, this is on the roadmap but I don't know when I'll find time to overhaul it to go on a screen

**Comment by DorianTheGrey** [comment]
A small workaround would be that you add a variable e.g. "WriteTelemetryDataToDatabank" and if set to true in the parameters and a databank is connected, it could write the most useful data to the databank. We could then simply connect through a PB and access it. Should be fairly easy for you to implement and takes the burden of you having to deal with these sidetopics (which are interesting but obviously not far up on the roadmap).

**Comment by Dimencia** [comment]
We attempted this in the past (see Cockpit branch), and it introduces major FPS problems to write frequently to the databank.  Otherwise all content has to be resized and adjusted to fit on a screen, which has strange resolution problems
