### ISSUE TITLE
Lose Throttle Position Indicator after entering Alt/Spd Hold (Alt-6) (Stay in Cruise Mode)

### ISSUE THREAD

**Issue by THBTX** [Dimencia/DU-Orbital-Hud#58]
When I exit Alt/Spd Hold (Alt-6), I am not taken out of Cruise mode.  I can manually change to travel mode, but it does not automatically do it.

**Comment by Dimencia** [comment]
Exiting cruise mode will set your throttle to 0 - this isn't something we want to do while you're flying, and we can't really guess how much throttle it would take to maintain the speed you're at

I was halfway through adding the fix when I realized it'll probably make a lot of people crash.  Best to have you manually disengage cruise so you're ready to throttle up immediately

**Comment by THBTX** [comment]
Sounds like a plan.  If not in the doc, please add. :)
