### ISSUE TITLE
pitch is calculated in wrong way

### ISSUE THREAD

**Issue by cola98765** [Dimencia/DU-Orbital-Hud#60]
current behaviour:
We look **down relative to the ship** and measure angle. when we roll angle increases.

expected behaviour:
We look **down towards ground** and measure angle. when we roll angle stays the same.

error lies in getPitch, here is changed function that solves this:
```
function getPitch(gravityDirection, forward)
	return ((math.acos(gravityDirection:dot(forward)) * constants.rad2deg)-90)	
end
```
Note lack of right vector. It's not needed in pitch calculations, only roll

**Comment by Archaegeo** [comment]
I am not sure this is correct.

1) The code works as is <grin>
2) in a real plane, when you roll, you must apply pitch control or pitch angle does change, thats the physics of flight.

Please provide more justification?

current pitch code:
`                function getPitch(gravityDirection, forward, right)
                    local horizontalForward = gravityDirection:cross(right):normalize_inplace() -- Cross forward?
                    local pitch = math.acos(utils.clamp(horizontalForward:dot(-forward), -1, 1)) * constants.rad2deg -- acos?
                    if horizontalForward:cross(-forward):dot(right) < 0 then pitch = -pitch end -- Cross right dot forward?
                    return pitch
                end
`

**Comment by Archaegeo** [comment]
Closing this for now
