### ISSUE TITLE
Newest update

### ISSUE THREAD

**Issue by ghost1257** [Dimencia/DU-Orbital-Hud#63]
Hi I found and fixed a problem in the code on unit stop line 8 and 13 was missing a closed bracket here is my fix it now the code works. 

if door and (atmo > 0 or (atmo == 0 and core_altitude < 10000) then ----- Original code
if door and (atmo > 0) or (atmo == 0 and core_altitude < 10000) then ----- My fix
and 
if forcefield and (atmo > 0 or (atmo == 0 and core_altitude < 10000)  then ----- Original Code
if forcefield and (atmo > 0) or (atmo == 0 and core_altitude < 10000)  then ------ My fix

it wasn't causing any problems really just my door was not auto opening but now it does when I'm on land.

**Comment by Archaegeo** [comment]
Yeah, updated in 4.065, what i get for not actually having a door connected to seat.  Thank you though.

**Comment by ghost1257** [comment]
Welcome
