### ISSUE TITLE
Max Speed, and too early braking

### ISSUE THREAD

**Issue by starhopper1** [Dimencia/DU-Orbital-Hud#7]
Hio, it would be nice i i could edit the max speed of the autopilot in the lua parameter.
I flew with your new version to alioth from thades and came out 10su before the planet, i guess this is a bug? :)

**Comment by Dimencia** [comment]
Max velocity is now configurable in ButtonHUD
Have not heard of anything like that issue, were you using turn & burn?  Auto-brake or autopilot?

**Comment by starhopper1** [comment]
I was using minimal hud and flying on autopilot from thades to alioth, i have to say i don´t like the buttonhud´s restriction in camera movment, i fly with keyboard only and use mouse just for looking around.^^

**Comment by Archaegeo** [comment]
you can fly keyboard only in ButtonHUD, its a configuration setting in unit.tick("APTick")

                -- USER DEFINABLE VARIABLE 
                local userControlScheme = "Virtual Joystick" --export: Set to "Virtual Joystick", "Mouse", or "Keyboard"

**Comment by Dimencia** [comment]
I've just updated buttonhud so that keyboard mode no longer auto-locks your view, and when your view is unlocked in keyboard it doesn't dim things, so that should help.
But all the physics fixes should still be present in minhud.  I'll see what I can find

**Comment by Dimencia** [comment]
There was an issue where the distance wasn't being calculated correctly, and maybe the errors could have compounded for a v large ship (or v small brake force).  That has been fixed, so hopefully it should fix your issue

**Comment by starhopper1** [comment]
Okay, will report back if the problem persits 👍

**Comment by Dimencia** [comment]
Have also fixed one other major bug with Alioth, which should hopefully stop giving everyone so much trouble because it's so fat.  Closing issue, reopen if you have further problems
