### ISSUE TITLE
Keys "c" and "space" for vertical engines not working

### ISSUE THREAD

**Issue by dertroglodyt** [Dimencia/DU-Orbital-Hud#75]
I'm using your script in keyboard(seat) + keyboard(internal) mode.
As soon as I autoconfigure with your script the keys for up/down stop working. Everything else seems to work fine. This happens with/without brakes or auto height on.
Standard autoconfigure reactivates the keys.

Is this intended or am I doing something worng?

Also: Thanks for sharing your work. :-)

**Comment by Archaegeo** [comment]
Tested with 4.145 and space and c are working as are alt-space and alt-c.  If you have an earlier version, please update.

**Comment by dertroglodyt** [comment]
You were correct. In newer version everything works fine. Thanks again.
