### ISSUE TITLE
Small HUD on Cockpit

### ISSUE THREAD

**Issue by Skyfulrucm** [Dimencia/DU-Orbital-Hud#76]
Hi, i installed the HUD like described.
But not in a chair, i installed it on a cockpit (Dont know if this is okay...)

Now i see the HUD in the right lower corner. Maybe a issue with a cockpit but not sure.
Insert a pic for you.
![small-hud](https://user-images.githubusercontent.com/58818284/95245887-03242280-0814-11eb-9a56-c6586f6acb85.png)

Cheers

Smourr

**Comment by Archaegeo** [comment]
If you look at the readme, we do not support cockpits.
