### ISSUE TITLE
[Feature Request] Anti-Grav Integration

### ISSUE THREAD

**Issue by timbrown81** [Dimencia/DU-Orbital-Hud#77]
As everyone continues to progress, more and more people will start having access to Anti-grav generators.  Unlike other features, AGG relies entirely on LUA for operation.  There is an open source AGG manager that uses a monitor and click events that can be used a a functional model  I think it would be a much more elegant solution to integrate such functionality into this HUD's button interface.  Touch screen is nice, but requires the pilot be in first person to interact with the AGG controller.

Necessary actions:

- Toggle AGG enable/disable
- Increment target altitude up/down - linked example has a toggle to change between increment of ten and hundred.  Could follow that pattern or have separate input for ten and hundred.
- Display of "Base" Altitude
-Potentially needs to connect AGG to seat.  Current implementation relies on user to manually connect.

[AntiGravityController](https://github.com/Helediron/dualuniverse/tree/master/AntiGravityController)

**Comment by Archaegeo** [comment]
Implemented.
