### ISSUE TITLE
HUD disappears and frames drop

### ISSUE THREAD

**Issue by babble720** [Dimencia/DU-Orbital-Hud#81]
This script is amazing, but with the last couple of builds, I am experiencing very low frames immediately before the HUD just disappears and I can't bring it back.   Its pretty consistent.  Usually on final entry into a planet :-)  I don't have much debug info except that it was working beautifully before.    If I had to guess, it may have some correlation with the re-entry altitude display?  or I'm just using it wrong, but like I said, I've been using it for a month now and just started happening recently

**Comment by Archaegeo** [comment]
We have 100% been unable to reproduce this.  Are you sure it wasnt when the server was laggy for everyone and about to be reset?

**Comment by babble720** [comment]
So the HUD disappeared, but the script kept running.  I could use alt 6 to hover, etc, so I'm not sure how lag would have impacted the code this way?   It happened three times one day.  Twice over water, and once on renentry to Alioth.   The only variables I changed were to toggle on auto-roll and switch to Keyboard mode.  Sorry I can't give you more.  Feel free to close this, you guys don't owe anyone support for such a great free tool.

**Comment by Archaegeo** [comment]
We just wish we could recreate it. Next time it happens try hitting alt-3 a couple of times, that should toggle between default widget view and HUD view.  Also if you get a chance, land, exit seat, and hit CTRL-L while looking at seat and tell us what error (if any) is shown down bottom.  (also your version number.

**Comment by Snirp88** [comment]
Hello, this exact thing was also happening to me yesterday. Probably 3 times. I tried hitting alt-3 and that wouldn't work. There was no script error any time It happened, just most of the hud disappearing. The words "Travel" would stay where they are, the version number on the bottom right would stay, and the outline around the numerical data in the top center would stay, but everything else was gone. 2 of the times it happened to me, was when I was toggling the radar hud in space with "V" the last time was when I was entering atmosphere. 
Settings: "Keyboard" free look toggle off. Usually in the first 3rd person option. I can look at the rest if it would help. 
version 4.2

**Comment by Snirp88** [comment]
![hud 2](https://user-images.githubusercontent.com/72705910/95688668-054a0080-0bc9-11eb-9478-303d3ae1eb0d.PNG)
![hud again](https://user-images.githubusercontent.com/72705910/95688669-0844f100-0bc9-11eb-8280-d74814b2e23d.PNG)
![hud lua](https://user-images.githubusercontent.com/72705910/95688671-0c710e80-0bc9-11eb-8d95-2cc24237cd14.PNG)
![hud](https://user-images.githubusercontent.com/72705910/95688673-0e3ad200-0bc9-11eb-9afe-7670f1a1a2ee.PNG)

**Comment by Snirp88** [comment]
i'm using "Keyboard" also, may be related to that?

**Comment by Snirp88** [comment]
Happened again from alioth to sanctuary right when the gravity indicator switched from counting down from alioth to counting up to Sanc. likely right when the LR trajectory switched between the planets.

**Comment by babble720** [comment]
I think I've narrowed it down to switching out of the hud for any reason, not just tab.  Inventory, Map, etc, the frames eventually get choppy and then the HUD disappears, just like the screenshot.  Maybe a memory leak?   If I don't switch out of the HUD I can't seem to reproduce, which sucks a little as it gets boring to just stare at that screen the whole trip...

**Comment by Snirp88** [comment]
Updating to 4.32 seems to have resolved the issue for me at least.
