### ISSUE TITLE
Fuel tank percent displayed not correct

### ISSUE THREAD

**Issue by izon2887** [Dimencia/DU-Orbital-Hud#82]
I am using v4.181 on my ship which uses two different sized fuel tanks for both atmo and space engines. The display on the HUD gives a consistent 99%-100% without changing even though the fuel is being consumed. Not sure if it has to do with the different sized fuel tanks or other issue.

**Comment by Archaegeo** [comment]
It shouldnt, and I am modifying the HUD this morning to use actual data from slotted tanks and calculated data from unslotted tanks.  Stand by for next version

**Comment by LoneBoco** [comment]
I fixed all of the fuel tank problems in pull request #87.
