### ISSUE TITLE
UserControlScheme is ignored/always VirtualJoystick

### ISSUE THREAD

**Issue by xHatti** [Dimencia/DU-Orbital-Hud#83]
Setting the userControlScheme to "Keyboard" wont do anything. The vehicle starts with a virtual joystick and ALT to toggle toggles between the virtualJoystick and freelook

No changes if "freeLookToggle" is changed

**Comment by Archaegeo** [comment]
Make sure your construct is set to Keyboard, also make sure if you update anything in Edit LUA Parameters, you wipe the databank first.

**Comment by Archaegeo** [comment]
The databank loads when you sit down, overwriting edit lua parameters.  To change settings, you must first wipe the databank (hit alt-7 2x in current version, or pick up, remove dynamic properties, put back down, rerun autoconf).
