### ISSUE TITLE
[Issue] Severe Performance Issue

### ISSUE THREAD

**Issue by Hyro-Shima** [Dimencia/DU-Orbital-Hud#85]
Hey guys.
after traveling more than ~ 5 - 15 minutes with this HUD, I get severe performance problems that seem to be directly correlated to using a control-seat with the orbital HUD.

By "severe performance problems" i mean the game becoming so laggy (<= 1 fps) that it is nearly impossible to take any action, leave alone bringing the ship to a save stop.

I can't tell you what happens or what goes wrong, but i can narrow down at least a little bit:
- this issue is related to the orbital HUD: 
  - when leaving the control seat the issue is gone instantly
  - when running the default autoconfig and re-entering the seat, the issue doesn't reappear
  - when re-entering the seat with orbital HUD enabled, the issue comes back after a short amount of time
- this issue is not bound to a single ship. i encountered it at least on two ships of mine (one being an S core, one being an M core ship)
- this issue happens both in atmosphere and in space
- the issue is doesn't seem to be correlated to a specific version of the HUD. i tried several versions, the newest being 4.2 the oldest being 3.90

If i can do anything to further investigate, please let me know as per answer to this issue.

Thanks & Happy debugging

**Comment by ghost1257** [comment]
I have encountered this also and what happens on mine if I let it play through is the hud stops working and it tells me CPU Overload

**Comment by Badley187** [comment]
> 
> 
> I have encountered this also and what happens on mine if I let it play through is the hud stops working and it tells me CPU Overload

i run in the same issue. after maybe 1h flying with autopilot. HUD crashed and i got a error like Control seat CPU Overload.

**Comment by ghost1257** [comment]
Yep same issue

**Comment by sirbum69** [comment]
i get all the time if when i am using the hud i move into another screen, say the map or tab out. if i dont do this then i dont have this issue. So i think it has to do with leaving the main screen at all.

**Comment by Blade244** [comment]
I also experience extreme frame drops, going down from 90-120fps to 6-20fps. It occurs after a certain flight time or faster if the chat window is opened. after some time it improves to ~60fps with noticeable stutters every second. During both phases (6-20fps and ~60fps)  disabling the HUD with Alt+3 brings it back to the normal frame rate except when moving the mouse outside the deadzone for the virtual joystick.

**Comment by ExecutedOnce** [comment]
Also have this issue, someone said it seems to work properly if you re-download and set it in your ship again. Tried that and it seemed to work fine yesterday, today it seems to cause huge frame loss. alt+f3 to hide the hud seems to bring fps right back up. Also lowered tickrate to 0.004 to no avail.

**Comment by Dimencia** [comment]
Frame loss happens if you press tab and click anything.  If framerate is being lost over time again, NQ may have reverted whatever patch fixed it last time.

Both of these problems should be reported to NQ via bug reports - ingame LUA should not be able to drop framerate that low without hitting a CPU overload, and the tab/click-anything bug has been here forever and they just need to fix it

**Comment by Archaegeo** [comment]
I am going to close this for now.  We are seeing pretty good performance now except the tab click bug which is on NQ.
