### ISSUE TITLE
[Feature Request] Button/Switch Integration

### ISSUE THREAD

**Issue by saladin1980** [Dimencia/DU-Orbital-Hud#86]
If Button/Switch Manually linked to Seat 
Then will turn on when getting in seat
else turn off when leaving the seat

Not sure if you can see about adding function like this to allow when you update that would otherwise be a manual process to add the lines in the code to turn on and off the manual switch.

**Comment by ownynotavailable** [comment]
> If Button/Switch Manually linked to Seat
> Then will turn on when getting in seat
> else turn off when leaving the seat
> 
> Not sure if you can see about adding function like this to allow when you update that would otherwise be a manual process to add the lines in the code to turn on and off the manual switch.

i agree with you but i also found a workaround. you link a door or forcefield to the seat, then u run the hud script, remove the link to the door/forcefield and then u connect the seat to a switch. from the switch u can use then relays and NOT operators as you wish.

**Comment by BoscoDCat** [comment]
I usually replace "DoorUnit" at the top of the script with "ManualSwitchUnit", then attach a switch to the seat and run the conf.

**Comment by Archaegeo** [comment]
Currently it works on a toggle.  If a manual switch is slotted to seat, it will toggle it when you sit and again when you stand.  So if you use like 5 hatches to a relay, relay to a manual switch, manual switch to seat, it will toggle the switch which will toggle all the hatches.
